name: Travokey Auth Application

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: self-hosted

    env:
      DB: mongodb+srv://crownintltechnology:crownintldev%402007@cluster0.co9fnr8.mongodb.net/auth
      PORT: 2999
      SECRET_KEY: SFSFGSDFW$%DFGDFGDFG2313
      JWT_SECRET: DFGDFGDFGD35345435FDGDFG
      AUTHAPI: https://soch.tech/authapi
      AccountApp: https://soch.tech/api
      NextApp: https://soch.tech/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Optimize Memory Usage
        run: export NODE_OPTIONS="--max_old_space_size=4096"

      - name: Stop Existing PM2 Process if It Exists
        run: |
          if pm2 list | grep -q "travokey-auth"; then
            pm2 delete "travokey-auth"
          else
            echo "PM2 process 'travokey-auth' not found, skipping stop command."
          fi

      - name: Start Application
        run: pm2 start npm --name "travokey-auth" -- run start

      - name: Deployment Status
        run: echo "Deployment successfully!"

        # pm2 start npm --name "travokey-frontend" -- run start
